apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  labels:
    app: flink
data:
  flink-conf.yaml: |+
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 2
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    taskmanager.rpc.port: 6122
    queryable-state.proxy.ports: 6125
    jobmanager.memory.process.size: 1024m
    taskmanager.memory.process.size: 1024m
    parallelism.default: 2
    kubernetes.cluster-id: foobar
    restart-strategy: fixed-delay
    restart-strategy.fixed-delay.attempts: 1024
    state.backend: rocksdb
    state.checkpoint-storage: filesystem
    state.storage.fs.memory-threshold: 5kb
    state.backend.local-recovery: true
    state.backend.persistent-volume-support: true
    state.backend.incremental: true
    state.checkpoints.dir: s3://flink/checkpoints
    taskmanager.state.local.root-dirs: /pv/localState
    # state.backend.rocksdb.localdir: /pv/rocksdb
    s3.path.style.access: true
    # minio settings
    env.java.opts: -Dcom.amazonaws.sdk.disableCertChecking
    s3.endpoint: minio.default
    s3.access-key: minio
    s3.secret-key: minio123
  log4j-console.properties: |+
    # This affects logging for both user code and Flink
    rootLogger.level = INFO
    rootLogger.appenderRef.console.ref = ConsoleAppender
    rootLogger.appenderRef.rolling.ref = RollingFileAppender

    # Uncomment this if you want to _only_ change Flink's logging
    #logger.flink.name = org.apache.flink
    #logger.flink.level = INFO

    # The following lines keep the log level of common libraries/connectors on
    # log level INFO. The root logger does not override this. You have to manually
    # change the log levels here.
    logger.akka.name = akka
    logger.akka.level = INFO
    logger.kafka.name= org.apache.kafka
    logger.kafka.level = INFO
    logger.hadoop.name = org.apache.hadoop
    logger.hadoop.level = INFO
    logger.zookeeper.name = org.apache.zookeeper
    logger.zookeeper.level = INFO
    logger.state.name = org.apache.flink.runtime.state
    logger.state.level = DEBUG
    logger.rocksdbcontrib.name = org.apache.flink.contrib.streaming.state.restore
    logger.rocksdbcontrib.level = DEBUG
    logger.jobmaster.name = org.apache.flink.runtime.jobmaster.JobMaster
    logger.jobmaster.level = DEBUG

    # Log all infos to the console
    appender.console.name = ConsoleAppender
    appender.console.type = CONSOLE
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n

    # Log all infos in the given rolling file
    appender.rolling.name = RollingFileAppender
    appender.rolling.type = RollingFile
    appender.rolling.append = false
    appender.rolling.fileName = ${sys:log.file}
    appender.rolling.filePattern = ${sys:log.file}.%i
    appender.rolling.layout.type = PatternLayout
    appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
    appender.rolling.policies.type = Policies
    appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
    appender.rolling.policies.size.size=100MB
    appender.rolling.strategy.type = DefaultRolloverStrategy
    appender.rolling.strategy.max = 10

    # Suppress the irrelevant (wrong) warnings from the Netty channel handler
    logger.netty.name = org.jboss.netty.channel.DefaultChannelPipeline
    logger.netty.level = OFF
